language: r

sudo: required

warnings_are_errors: true

r-packages:
- knitr
- rmarkdown

r_check_args: --no-vignettes --no-build-vignettes

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'

